// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Document struct {
	ID          int32        `json:"id"`
	PermitID    int32        `json:"permit_id"`
	DocumentUrl string       `json:"document_url"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Fee struct {
	ID        int32        `json:"id"`
	PermitID  int32        `json:"permit_id"`
	Amount    string       `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Notification struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Message   string         `json:"message"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Payment struct {
	ID            int32        `json:"id"`
	UserID        int32        `json:"user_id"`
	PermitID      int32        `json:"permit_id"`
	Amount        string       `json:"amount"`
	Status        string       `json:"status"`
	PaymentMethod string       `json:"payment_method"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type Permit struct {
	ID          int32        `json:"id"`
	UserID      int32        `json:"user_id"`
	Description string       `json:"description"`
	Status      string       `json:"status"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
